package com.xiyuan.template.model;

public class TbTest {
    /**
     * 主键
     */
    private Integer id;

    /**
     * 名字
     */
    private String name;

    /**
     * 内容
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.id
     *
     * @return the value of tb_test.id
     *
     * @mbggenerated Thu Dec 01 15:06:05 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.id
     *
     * @param id the value for tb_test.id
     *
     * @mbggenerated Thu Dec 01 15:06:05 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.name
     *
     * @return the value of tb_test.name
     *
     * @mbggenerated Thu Dec 01 15:06:05 CST 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.name
     *
     * @param name the value for tb_test.name
     *
     * @mbggenerated Thu Dec 01 15:06:05 CST 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_test.content
     *
     * @return the value of tb_test.content
     *
     * @mbggenerated Thu Dec 01 15:06:05 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_test.content
     *
     * @param content the value for tb_test.content
     *
     * @mbggenerated Thu Dec 01 15:06:05 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }
}